import type { Config } from "tailwindcss";
import typography from "@tailwindcss/typography";

const config: Config = {
    darkMode: ["class"],
    content: [
        "./src/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                bg: "var(--bg)",
                background: "var(--bg)",
                surface: {
                    DEFAULT: "var(--surface)",
                    elevated: "var(--surface-elevated)",
                },
                fg: "var(--fg)",
                muted: "var(--muted)",
                subtle: "var(--subtle)",
                border: {
                    DEFAULT: "var(--border)",
                    soft: "var(--border-soft)",
                    focus: "var(--border-focus)",
                },
                accent: {
                    DEFAULT: "var(--accent)",
                    soft: "var(--accent-soft)",
                    fg: "var(--accent-fg)",
                    50: "var(--terracotta-50)",
                    100: "var(--terracotta-100)",
                    200: "var(--terracotta-200)",
                    300: "var(--terracotta-300)",
                    400: "var(--terracotta-400)",
                    500: "var(--terracotta-500)",
                    600: "var(--terracotta-600)",
                    700: "var(--terracotta-700)",
                    800: "var(--terracotta-800)",
                    900: "var(--terracotta-900)",
                },
                warm: {
                    50: "var(--warm-50)",
                    100: "var(--warm-100)",
                    200: "var(--warm-200)",
                    300: "var(--warm-300)",
                    400: "var(--warm-400)",
                    500: "var(--warm-500)",
                    600: "var(--warm-600)",
                    700: "var(--warm-700)",
                    800: "var(--warm-800)",
                    900: "var(--warm-900)",
                },
                success: {
                    DEFAULT: "var(--success)",
                    light: "var(--success-light)",
                    50: "var(--green-50)",
                    600: "var(--green-600)",
                },
                warning: {
                    DEFAULT: "var(--warning-fg)",
                    light: "var(--warning-light)",
                    50: "var(--warning-bg)",
                    600: "var(--warning-fg)",
                },
                danger: {
                    DEFAULT: "var(--danger)",
                    light: "var(--danger-light)",
                    50: "var(--danger-bg)",
                    600: "var(--red-600)",
                },
                error: {
                    DEFAULT: "var(--danger)",
                    light: "var(--danger-light)",
                    50: "var(--danger-bg)",
                    600: "var(--red-600)",
                },
                link: {
                    DEFAULT: "var(--link)",
                    hover: "var(--link-hover)",
                    light: "var(--link-light)",
                },
                nav: {
                    purple: "var(--nav-purple)",
                    cyan: "var(--nav-cyan)",
                    green: "var(--nav-green)",
                },
                terminal: {
                    prompt: "var(--terminal-green)",
                    cursor: "var(--terminal-terracotta)",
                },
                mac: {
                    red: "var(--mac-red)",
                    yellow: "var(--mac-yellow)",
                    green: "var(--mac-green)",
                },
            },
            spacing: {
                'token-0': "var(--space-0)",
                'token-px': "var(--space-px)",
                'token-xs': "var(--space-xs)",
                'token-sm': "var(--space-sm)",
                'token-md': "var(--space-md)",
                'token-lg': "var(--space-lg)",
                'token-xl': "var(--space-xl)",
                'token-2xl': "var(--space-2xl)",
                'token-3xl': "var(--space-3xl)",
                'token-4xl': "var(--space-4xl)",
                'token-5xl': "var(--space-5xl)",
                'token-section': "var(--section-gap)",
                'token-section-sm': "var(--section-gap-sm)",
                'token-header': "var(--header-height)",
                'token-gap': "var(--space-gap)",
                'token-gap-sm': "var(--space-gap-sm)",
                'token-gap-lg': "var(--space-gap-lg)",
            },
            maxWidth: {
                'token-sm': "var(--container-sm)",
                'token-md': "var(--container-md)",
                'token-lg': "var(--container-lg)",
                'token-xl': "var(--container-xl)",
                'token-2xl': "var(--container-2xl)",
                'token-content': "var(--container-content)",
                'token-wide': "var(--container-wide)",
            },
            borderRadius: {
                'token-sm': "var(--radius-sm)",
                'token-md': "var(--radius-md)",
                'token-lg': "var(--radius-lg)",
                'token-xl': "var(--radius-xl)",
                'token-2xl': "var(--radius-2xl)",
                'token-full': "var(--radius-full)",
                'token-card': "var(--card-radius)",
                'token-button': "var(--button-radius)",
                'token-input': "var(--input-radius)",
                'token-badge': "var(--badge-radius)",
            },
            boxShadow: {
                'token-sm': "var(--shadow-sm)",
                'token-md': "var(--shadow-md)",
                'token-lg': "var(--shadow-lg)",
                'token-card': "var(--card-shadow)",
                'token-card-hover': "var(--card-shadow-hover)",
                'token-header': "var(--header-shadow)",
                'token-button': "var(--button-shadow)",
                card: "var(--card-shadow)",
                header: "var(--header-shadow)",
            },
            transitionDuration: {
                'token-fast': "var(--duration-fast)",
                'token-normal': "var(--duration-normal)",
                'token-slow': "var(--duration-slow)",
            },
            transitionTimingFunction: {
                'token-default': "var(--ease-default)",
                'token-in': "var(--ease-in)",
                'token-out': "var(--ease-out)",
            },
            fontFamily: {
                mono: ["var(--font-mono)", "monospace"],
                sans: ["var(--font-sans)", "sans-serif"],
                serif: ["var(--font-serif)", "serif"],
            },
            fontSize: {
                'token-xs': "var(--font-size-xs)",
                'token-sm': "var(--font-size-sm)",
                'token-base': "var(--font-size-base)",
                'token-lg': "var(--font-size-lg)",
                'token-xl': "var(--font-size-xl)",
                'token-2xl': "var(--font-size-2xl)",
                'token-3xl': "var(--font-size-3xl)",
                'token-4xl': "var(--font-size-4xl)",
                'token-5xl': "var(--font-size-5xl)",
            },
            lineHeight: {
                'token-none': "var(--line-height-none)",
                'token-tight': "var(--line-height-tight)",
                'token-snug': "var(--line-height-snug)",
                'token-normal': "var(--line-height-normal)",
                'token-relaxed': "var(--line-height-relaxed)",
                'token-loose': "var(--line-height-loose)",
            },
            fontWeight: {
                'token-normal': "var(--font-weight-normal)",
                'token-medium': "var(--font-weight-medium)",
                'token-semibold': "var(--font-weight-semibold)",
            },
            letterSpacing: {
                'token-tight': "var(--letter-spacing-tight)",
                'token-normal': "var(--letter-spacing-normal)",
                'token-wide': "var(--letter-spacing-wide)",
                'token-caps': "var(--letter-spacing-caps)",
            },
            zIndex: {
                'token-dropdown': "var(--z-dropdown)",
                'token-sticky': "var(--z-sticky)",
                'token-fixed': "var(--z-fixed)",
                'token-overlay': "var(--z-overlay)",
                'token-modal': "var(--z-modal)",
                'token-popover': "var(--z-popover)",
                'token-tooltip': "var(--z-tooltip)",
            },
            typography: {
                DEFAULT: {
                    css: {
                        color: "var(--fg)",
                        a: {
                            color: "var(--link)",
                            textDecoration: "underline",
                            textDecorationThickness: "1px",
                            textUnderlineOffset: "2px",
                            transition: "color 150ms var(--ease-default)",
                            "&:hover": {
                                color: "var(--link-hover)",
                            },
                        },
                        'h1, h2, h3, h4, h5, h6': {
                            fontFamily: "var(--font-serif)",
                            color: "var(--fg)",
                            fontWeight: "500",
                            letterSpacing: "0",
                        },
                        code: {
                            color: "var(--accent)",
                            backgroundColor: "var(--warm-100)",
                            padding: "0.15rem 0.4rem",
                            borderRadius: "var(--radius-sm)",
                            fontSize: "0.875em",
                        },
                        'code::before': {
                            content: '""',
                        },
                        'code::after': {
                            content: '""',
                        },
                        blockquote: {
                            borderLeftColor: "var(--accent)",
                            color: "var(--muted)",
                        },
                    },
                },
            },
        },
    },
    plugins: [typography],
};
export default config;
